---
- name: Patch Linux Servers (RHEL, CentOS, Ubuntu)
  hosts: linux_servers
  become: yes
  gather_facts: yes

  tasks:

    - name: Identify OS type
      debug:
        msg: "Patching {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Update packages on RHEL/CentOS (YUM/DNF)
      when: ansible_os_family == "RedHat"
      block:
        - name: Clean metadata
          ansible.builtin.command: dnf clean all
          register: clean_output
          changed_when: false

        - name: Update all packages
          ansible.builtin.dnf:
            name: '*'
            state: latest
          register: rhel_update

        - name: Show updated packages (RHEL/CentOS)
          debug:
            var: rhel_update.changes

    - name: Update packages on Ubuntu (APT)
      when: ansible_os_family == "Debian"
      block:
        - name: Update apt cache
          ansible.builtin.apt:
            update_cache: yes
          register: apt_cache

        - name: Upgrade all packages
          ansible.builtin.apt:
            upgrade: dist
            autoclean: yes
            autoremove: yes
          register: ubuntu_update

        - name: Show updated packages (Ubuntu)
          debug:
            var: ubuntu_update.changed

    - name: Reboot if required
      ansible.builtin.reboot:
        msg: "Rebooting after patching"
        connect_timeout: 5
        reboot_timeout: 600
        test_command: whoami
      when: >
        (rhel_update is defined and rhel_update.changed) or
        (ubuntu_update is defined and ubuntu_update.changed)
