---
- name: Pre-Patching Checks on Windows Servers
  hosts: windows_servers
  gather_facts: yes
  vars:
    pre_report_path: "C:\\Temp\\windows_pre_patch_{{ inventory_hostname }}.txt"

  tasks:
    - name: Pre-Patching: Display starting message
      ansible.builtin.debug:
        msg: "Starting pre-patching checks on {{ inventory_hostname }}"

    - name: Check system uptime
      ansible.windows.win_shell: |
        (Get-CimInstance Win32_OperatingSystem).LastBootUpTime
      register: uptime_out

    - name: Check free disk space
      ansible.windows.win_shell: |
        Get-PSDrive C | Select-Object Used, Free
      register: disk_out

    - name: Save pre-patching report
      ansible.windows.win_copy:
        dest: "{{ pre_report_path }}"
        content: |
          ===== PRE-PATCH REPORT =====
          Hostname: {{ inventory_hostname }}
          Uptime: {{ uptime_out.stdout }}
          Disk Usage (C: drive): {{ disk_out.stdout }}

    - name: Display pre-check completion
      ansible.builtin.debug:
        msg: "Pre-patching checks completed for {{ inventory_hostname }}. Report: {{ pre_report_path }}"
